import type { Metadata } from "next";
import { AuthProvider } from "./Provider";
import { Inter } from "next/font/google";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="dark:bg-boxdark-2 dark:text-bodydark">
        <AuthProvider>{children}</AuthProvider>
      </body>
    </html>
  );
}
